export const resList = [
  {
    info: {
      id: "123456",
      name: "Pizza Paradise",
      cloudinaryImageId: "rng/md/carousel/production/pizza123",
      locality: "MG Road",
      areaName: "Central District",
      costForTwo: "₹400 for two",
      cuisines: ["Pizza", "Italian", "Fast Food"],
      avgRating: 4.3,
      avgRatingString: "4.3",
      totalRatingsString: "10K+ ratings",
      veg: false,
      sla: { deliveryTime: 30, lastMileTravel: 3.5, slaString: "30 mins" },
      aggregatedDiscountInfoV3: { header: "50% OFF", subHeader: "UPTO ₹100" },
    },
  },
  {
    info: {
      id: "234567",
      name: "Burger Hub",
      cloudinaryImageId: "rng/md/carousel/production/burger234",
      locality: "Brigade Road",
      areaName: "Downtown",
      costForTwo: "₹300 for two",
      cuisines: ["Burgers", "American", "Fast Food"],
      avgRating: 4.1,
      avgRatingString: "4.1",
      totalRatingsString: "8K+ ratings",
      veg: false,
      sla: { deliveryTime: 25, lastMileTravel: 2.1, slaString: "25 mins" },
      aggregatedDiscountInfoV3: { header: "40% OFF", subHeader: "UPTO ₹80" },
    },
  },
  {
    info: {
      id: "345678",
      name: "Green Bites",
      cloudinaryImageId: "rng/md/carousel/production/green345",
      locality: "Koramangala",
      areaName: "South Bangalore",
      costForTwo: "₹250 for two",
      cuisines: ["Healthy", "Salads", "Vegan"],
      avgRating: 4.5,
      avgRatingString: "4.5",
      totalRatingsString: "5K+ ratings",
      veg: true,
      sla: { deliveryTime: 35, lastMileTravel: 4.2, slaString: "35 mins" },
      aggregatedDiscountInfoV3: { header: "20% OFF", subHeader: "UPTO ₹60" },
    },
  },
  {
    info: {
      id: "456789",
      name: "Spice Kingdom",
      cloudinaryImageId: "rng/md/carousel/production/spice456",
      locality: "Indiranagar",
      areaName: "East Bangalore",
      costForTwo: "₹500 for two",
      cuisines: ["Indian", "Biryani", "Kebabs"],
      avgRating: 4.7,
      avgRatingString: "4.7",
      totalRatingsString: "20K+ ratings",
      veg: false,
      sla: { deliveryTime: 45, lastMileTravel: 5.0, slaString: "45 mins" },
      aggregatedDiscountInfoV3: { header: "30% OFF", subHeader: "UPTO ₹120" },
    },
  },
  {
    info: {
      id: "567890",
      name: "Chinese Dragon",
      cloudinaryImageId: "rng/md/carousel/production/chinese567",
      locality: "Whitefield",
      areaName: "East Bangalore",
      costForTwo: "₹350 for two",
      cuisines: ["Chinese", "Asian", "Noodles"],
      avgRating: 4.0,
      avgRatingString: "4.0",
      totalRatingsString: "6K+ ratings",
      veg: false,
      sla: { deliveryTime: 40, lastMileTravel: 6.3, slaString: "40 mins" },
      aggregatedDiscountInfoV3: {
        header: "FLAT ₹100 OFF",
        subHeader: "ON ORDERS ABOVE ₹299",
      },
    },
  },
  {
    info: {
      id: "678901",
      name: "Dessert Delight",
      cloudinaryImageId: "rng/md/carousel/production/dessert678",
      locality: "HSR Layout",
      areaName: "South Bangalore",
      costForTwo: "₹200 for two",
      cuisines: ["Desserts", "Ice Cream", "Cakes"],
      avgRating: 4.4,
      avgRatingString: "4.4",
      totalRatingsString: "12K+ ratings",
      veg: true,
      sla: { deliveryTime: 20, lastMileTravel: 1.8, slaString: "20 mins" },
      aggregatedDiscountInfoV3: { header: "60% OFF", subHeader: "UPTO ₹150" },
    },
  },
  {
    info: {
      id: "789012",
      name: "Sushi Station",
      cloudinaryImageId: "rng/md/carousel/production/sushi789",
      locality: "UB City",
      areaName: "Central Bangalore",
      costForTwo: "₹800 for two",
      cuisines: ["Japanese", "Sushi", "Asian"],
      avgRating: 4.8,
      avgRatingString: "4.8",
      totalRatingsString: "4K+ ratings",
      veg: false,
      sla: { deliveryTime: 50, lastMileTravel: 7.1, slaString: "50 mins" },
      aggregatedDiscountInfoV3: { header: "10% OFF", subHeader: "UPTO ₹200" },
    },
  },
  {
    info: {
      id: "890123",
      name: "South Spice",
      cloudinaryImageId: "rng/md/carousel/production/south890",
      locality: "Jayanagar",
      areaName: "South Bangalore",
      costForTwo: "₹300 for two",
      cuisines: ["South Indian", "Dosa", "Idli"],
      avgRating: 4.6,
      avgRatingString: "4.6",
      totalRatingsString: "15K+ ratings",
      veg: true,
      sla: { deliveryTime: 30, lastMileTravel: 2.9, slaString: "30 mins" },
      aggregatedDiscountInfoV3: {
        header: "FLAT ₹75 OFF",
        subHeader: "ON ORDERS ABOVE ₹199",
      },
    },
  },
];
